//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAYILERSATISPROJESI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BayilerSet
    {
        public int Id { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public int BayiId { get; set; }
        public string Sifre { get; set; }
    }
}
