//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAYILERSATISPROJESI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROJEEntities : DbContext
    {
        public PROJEEntities()
            : base("name=PROJEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BayilerSet> BayilerSets { get; set; }
        public virtual DbSet<urunSet> urunSets { get; set; }
        public virtual DbSet<UsersSet> UsersSets { get; set; }
        public virtual DbSet<Siparisler> Siparislers { get; set; }
    }
}
