//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAYILERSATISPROJESI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNEKLE
    {
        public int Id { get; set; }
        public Nullable<int> URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> STOK { get; set; }
        public byte[] RESIM { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
