//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAYILERSATISPROJESI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunSet
    {
        public int Id { get; set; }
        public string Isim { get; set; }
        public decimal Fiyat { get; set; }
        public int StokAdeti { get; set; }
        public string Resim { get; set; }
        public string Aciklama { get; set; }
    }
}
