//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAYILERSATISPROJESI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersSet
    {
        public int Id { get; set; }
        [DisplayName("Kullanýcý Adý")]
        [Required(ErrorMessage = "Bu alaný doldurunuz!!")]
        public string KullaniciAdi { get; set; }

        [DisplayName("Þifre")]
        [Required(ErrorMessage = "Bu alaný doldurunuz!!")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
       
        public string LoginErrorMessage { get; set; }
    }
}
