//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAYILERSATISPROJESI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }
        [DisplayName("Kullanýcý Adý")]
        [Required(ErrorMessage = "Bu alaný doldurunuz!!!")]
        public string KullaniciAdi { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Þifre")]
        [Required(ErrorMessage = "Bu alaný doldurunuz!!!")]
        public string Sifre { get; set; }
        public string GiriþHataMesajý { get; set; }
    }
}
